### ISSUE TITLE
Error dialogs don't stay visible long enough

### ISSUE THREAD

**Issue by robertmclaws** [akorchev/radzen#15]
I had an issue with an app not compiling. It was missing the `\src\assets\img` folder, so webpack wouldn't run. RadZen threw a dialog warning me about the issue, but it was only visible for < 3 seconds. There needs to be a persistent "Errors" pane like in Visual Studio when an issue comes up, so that you can see what the issue is and handle it.

PS What's up, @akorchev 😃

**Comment by akorchev** [comment]
Hi Robert!

You are absolutely right. We have some plans for an output pane similar to Visual Studio. Actually we want to make the entire UI like Visual Studio so it feels familiar. Here is a mockup.
![radzen revamp](https://cloud.githubusercontent.com/assets/454726/22728965/33c73c9a-ede9-11e6-86c1-1301a147c232.png)

**Comment by akorchev** [comment]
Error dialogs no longer close by themselves. They also allow you to copy the message and or open the log file.
