### ISSUE TITLE
Allow custom attribute or rendered code customization

### ISSUE THREAD

**Issue by fileman** [akorchev/radzen#17]
For example if I want drag & drop between two datagrid as shown in this [page](http://primefaces.org/primeng/#/dragdrop), I need to add pDraggable and pDroppable attribute to div. 
In MS Lightswitch HTML Client (R.I.P.) there is "Edit PostRender code" so whe can write something like this:
`element.setAttribute("pDroppable","dd")`
with HTML result:
`<div class="..." pDroppable="dd">`

**Comment by valentinstoychev** [comment]
@akorchev what do you think will be the best way to achieve this?

@fileman - With Radzen you can edit the code of the app freely after using the designer. We are creating special files which extend the functionality created by the designer and you can set any custom code there which will NOT be overridden by the designer when you make changes. The output of Radzen is a standard Angular app which complies with the Angular CLI recommendations. You can use any IDE to edit the code.

@akorchev or @enchev can you please send a code snippet how this can be achieved?
