### ISSUE TITLE
OData ETag

### ISSUE THREAD

**Issue by fileman** [akorchev/radzen#18]
In Form if entity has @odata.etag put this in If-Match / If-None-Match Header for submit

**Comment by valentinstoychev** [comment]
We will do this for the beta as well! Keet them coming :)

**Comment by fileman** [comment]
with auto generated columns there is a problem with @odata.etag, error "Unable to get property 'etag' of undefined or null reference".

**Comment by akorchev** [comment]
This should be fixed in beta 1. There are no longer autogenerated columns at runtime. The user has to generate them in design time which should skip @odata.etag.
