### ISSUE TITLE
Simplify Value field 

### ISSUE THREAD

**Issue by fileman** [akorchev/radzen#19]
In Value field we must enter 2 special char ${ before end one at the end } of result, parameter, etc.. since in this field they are required, I want to propose some alternatives:

1. Precompile with these character the value field that adds a parameter or an event ( ex. ${} )
2. Add this character in code, so we can simply write result, parameter ( ex. result.value instead of ${result.value} )

**Comment by akorchev** [comment]
Thanks for the feedback! Indeed entering that special syntax is cumbersome at the moment. We plan a different UI for it which we hope would simplify things. When the user types in the textbox the data will be treated as a constant. A separate button for databinding would allow the user to pick a property which to bind the value to. Does this make more sense?
