### ISSUE TITLE
Property case sensitive compile error

### ISSUE THREAD

**Issue by fileman** [akorchev/radzen#20]
Beta1 when I use "Assistito" instead of "assistito" this error prevent run

"Radzen/client/src/app/assistito-edit/assistito-edit-generated.component.ts (55,12): Property 'assistito' does not exist on type 'AssistitoEditGenerated'.)[39m[22m
webpack: Failed to compile."

**Comment by akorchev** [comment]
Could you give us more details about this problem? Where do you use 'Assistito'? Is it a property of the model or what? A screenshot would help.

**Comment by fileman** [comment]
I forgot to attach it!
![property name case sensitive](https://cloud.githubusercontent.com/assets/17230763/24542876/a01b8cd4-15fd-11e7-9430-77f40ede036d.png)

**Comment by akorchev** [comment]
Any chance to attach the generated source code of AssistitoEditGenerated? I am still having trouble understanding the issue.

**Comment by enchev** [comment]
Hey @fileman,

Do you still have such error?

Thanks

**Comment by fileman** [comment]
Hi, no it's solved!
thanks
