### ISSUE TITLE
Grid column wrong property after delete

### ISSUE THREAD

**Issue by fileman** [akorchev/radzen#21]
Beta1 When I delete an auto-generated column as "Id" displays the wrong until I change page and then return

![pre_delete_id](https://cloud.githubusercontent.com/assets/17230763/24516781/286dd5d8-157c-11e7-9da3-3700e54ca505.png) ![after_delete_id](https://cloud.githubusercontent.com/assets/17230763/24516805/39f61fd6-157c-11e7-9291-0d1c9e1df739.png)

**Comment by akorchev** [comment]
Reproduced and fixed. Thanks!
