### ISSUE TITLE
Fields reorder in grid and forms

### ISSUE THREAD

**Issue by fileman** [akorchev/radzen#22]
Allow to change order of fields in grid and forms.

**Comment by joshbooker** [comment]
+1 good suggestion. FWIW, you can easily move fields around by editing the form metadata using a text editor such as vscode.

**Comment by fileman** [comment]
@joshbooker yes is possible, but not much RAD style ... with Lightswith we are used well

**Comment by akorchev** [comment]
We will add reordering soon! Stay tuned. We also plan a change in the way form fields are defined. The current implementation is not optimal.

**Comment by akorchev** [comment]
We implemented form field and data grid column reordering in the 1.1.3 release.
