### ISSUE TITLE
Edit Data Source hangs when Inferring Schema from Azure SQL Database

### ISSUE THREAD

**Issue by PaulSPatterson** [akorchev/radzen#24]
Seems that attempting to infer a schema from an Azure SQL Database causes the Edit Data Source page to hang. 

Is Azure SQL supported when attempting to create a SQL Data source?

**Comment by akorchev** [comment]
We fixed one issue with Azure and there is another known one when your schema has `datetime2` columns. We are working on fixing it. Will update this issue when this is done.

**Comment by PaulSPatterson** [comment]
Thanks Atanas, 

Is there a log file or something that I can poke at should further issues arise? That way I can be more specific about things I dig up.

**Comment by akorchev** [comment]
We maintain a changelog [here](https://github.com/akorchev/radzen/blob/master/CHANGELOG.md).

**Comment by PaulSPatterson** [comment]
Apologies, I meant a log file that the application rights to. When app errors occur, where can I go to see what exceptions have been raised?

**Comment by akorchev** [comment]
This is something we will work on for the next release. Radzen should both create a log file when there are errors and display unexpected exceptions.

**Comment by PaulSPatterson** [comment]
Atanas, I dug a little deeper into this issue, and found that the Infer Schema feature hangs when attempting to determine a schema that uses the timestamp data type.

**Comment by akorchev** [comment]
We fixed a few issues in the newly released 1.0.2 version. You can check it out.

**Comment by enchev** [comment]
Both DateTime and TimeStamp issues fixed. I'm closing this.
