### ISSUE TITLE
SQL Data Source Connection Problem

### ISSUE THREAD

**Issue by adaptulf** [akorchev/radzen#26]
Hi,

I've problem to connct to SQL Server Express. Get "Failed to connect to localhost:1433 - Couldn't not connect (sequence). Tried on two machines , different settings, TCP IP Enable, Turning off firewalls ...
Hope you maybe have a hint :)   Is it it possible to set a named instance or is it just localhost and sa ?

Best Regards

Ulf

**Comment by akorchev** [comment]
Hi Ulf,

We are aware of this limitation and fixed it in the internal builds. The fix will go official soon. You can send an email to info@radzen.com to get a link to the hotfix build.

One can now specify a named instance and or use dynamic ports. The "Port" textbox has been removed. One can omit the port if it is the default or dynamically assigned. Or specify it in the "Server" textbox.

## Examples

### Server with named instance

Server: `localhost\SQLEXPRESS`

### Server with port

Server: `localhost,1433`

### Server with port and local instance

Server `localhost,1433\SQLEXPRESS`

**Comment by adaptulf** [comment]
Hi,

Now it worked  ! :) =>  Server: localhost\SQLEXPRESS with the the hotfix version.

Think Pipe and TCP/IP has to enabled in Sql Server Configuration Manager - Sql Network Configuration, SQL Server Browser Service running and Sql Server Service restarted (for localhost to be recognized - normally i use .\SQLEXPRESS or computername\SQLEXPRESS).

Thanks for the instruction and hotfix !

Ulf

**Comment by akorchev** [comment]
Yes, Radzen supports only TCP/IP connections at this time. No named pipes at the moment.
