### ISSUE TITLE
SQL Server Spatial Data Types

### ISSUE THREAD

**Issue by PaulSPatterson** [akorchev/radzen#27]
Would love to see support for[ SQL Server Spatial data types ](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview). Especially the Geography data type, with a feature to automagically render the mapping on a page.

**Comment by akorchev** [comment]
Oh boy! This could be a killer feature. Do you know of anything that supports visualizing SQL Server spatial data types? Sample app or demo perhaps?
