### ISSUE TITLE
Project file does not exist

### ISSUE THREAD

**Issue by carlosgjr** [akorchev/radzen#28]
Getting Error when running project:

dotnet: The current project is not valid because of the following errors:
C:\Users\cgonz\Documents\Visual Studio 2015\Projects\RADZEN\biamp\server(1,0): error DOTNET1017: Project file does not exist 'C:\Users\cgonz\Documents\Visual Studio 2015\Projects\RADZEN\biamp\server\project.json'.

![2017-04-21_23-48-14](https://cloud.githubusercontent.com/assets/7093207/25301455/1c21d18a-26ed-11e7-8cfa-4ed4db9b8755.png)

**Comment by enchev** [comment]
Most probably you do not have latest .NET Core 1.1 . Can you check this? You can get it from here:
https://www.microsoft.com/net/core

**Comment by carlosgjr** [comment]
Installed and get a new error.  I will pick this up in the morning



dotnet: C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error :
Unable to resolve 'Microsoft.DotNet.Watcher.Tools (>= 1.0.0)' for
'.NETCoreApp,Version=v1.0'. [C:\Users\cgonz\Documents\Visual Studio
2015\Projects\RADZEN\biamp\server\project.csproj]

dotnet: C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error :
Value cannot be null. [C:\Users\cgonz\Documents\Visual Studio
2015\Projects\RADZEN\biamp\server\project.csproj]
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Parameter
name: path [C:\Users\cgonz\Documents\Visual Studio
2015\Projects\RADZEN\biamp\server\project.csproj]


On Sat, Apr 22, 2017 at 12:07 AM, Vladimir Enchev <notifications@github.com>
wrote:
>
> Most probably you do not have latest .NET Core 1.1 . Can you check this?
You can get it from here:

**Comment by akorchev** [comment]
From the path it still looks as if you are using an older version of dotnet: 
C:\Program Files\dotnet\sdk\ **1.0.1** \

**Comment by carlosgjr** [comment]
I have updated .net core

I get this error:

[image: Inline image 1]

**Comment by akorchev** [comment]
Hi could you please try attaching the image again?

**Comment by carlosgjr** [comment]
**Output text:**

radzen: Generating code ...
radzen: Code generation done in 801ms.
dotnet: Models\AzureMetadata\ColumnMetadatum.cs(217,27): error CS0102: The type 'ColumnMetadatum' already contains a definition for 'TableMetadatum' [C:\Users\cgonz\Documents\Visual Studio 2015\Projects\RADZEN\biamp\server\project.csproj]
Models\AzureMetadata\FileConnectionMetadatum.cs(106,22): error CS0102: The type 'FileConnectionMetadatum' already contains a definition for 'Delimiter' [C:\Users\cgonz\Documents\Visual Studio 2015\Projects\RADZEN\biamp\server\project.csproj]
Models\AzureMetadata\TableMetadatum.cs(130,32): error CS0102: The type 'TableMetadatum' already contains a definition for 'ConnectionMetadatum' [C:\Users\cgonz\Documents\Visual Studio 2015\Projects\RADZEN\biamp\server\project.csproj]

dotnet: 

dotnet: The build failed. Please fix the build errors and run again.

**Comment by akorchev** [comment]
This error sounds similar to #30. We are currently working on a fix.

**Comment by enchev** [comment]
Hey @carlosgjr,

We've fixed #30 and 1.0.4 is just released.
