### ISSUE TITLE
Model Code Generation Error

### ISSUE THREAD

**Issue by PETERHUP** [akorchev/radzen#30]
the Errors (occurs in most of my tables)

1>Models\Sample\SampleCode.cs(52,17,52,21): error CS0102: The type 'SampleCode' already contains a definition for 'User'
1>Models\Sample\SampleCode.cs(68,19,68,25): error CS0102: The type 'SampleCode' already contains a definition for 'Lookup'
1>Models\Sample\SampleCode.cs(98,19,98,25): error CS0102: The type 'SampleCode' already contains a definition for 'Lookup'

Generated code Sample:
[Models.SampleDB.SampleCode.txt](https://github.com/akorchev/radzen/files/952872/Models.SampleDB.SampleCode.txt)

Structure of my tables in MSSQL database:

CREATE TABLE [dbo].[SampleCode](
	[SampleCodeID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[Detail] [text] NULL,
	[Reference] [nvarchar](10) NULL,
	[CategoryID] [int] NULL,
	[ClassificationID] [int] NULL,
	[TypeID] [int] NOT NULL,
	[AddedByUserID] [int] NOT NULL,
	[AddedDate] [datetime] NOT NULL,
	[ChangedByUserID] [int] NULL,
	[ChangedDate] [datetime] NULL,
 CONSTRAINT [PK_dbo.SampleCode] PRIMARY KEY CLUSTERED 
(
	[SampleCodeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[SampleCode]  WITH CHECK ADD  CONSTRAINT [FK_dbo.SampleCode_dbo.Lookup_CategoryID] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Lookup] ([LookupID])
ALTER TABLE [dbo].[SampleCode] CHECK CONSTRAINT [FK_dbo.SampleCode_dbo.Lookup_CategoryID]

ALTER TABLE [dbo].[SampleCode]  WITH CHECK ADD  CONSTRAINT [FK_dbo.SampleCode_dbo.Lookup_ClassificationID] FOREIGN KEY([ClassificationID])
REFERENCES [dbo].[Lookup] ([LookupID])
ALTER TABLE [dbo].[SampleCode] CHECK CONSTRAINT [FK_dbo.SampleCode_dbo.Lookup_ClassificationID]

ALTER TABLE [dbo].[SampleCode]  WITH CHECK ADD  CONSTRAINT [FK_dbo.SampleCode_dbo.Lookup_TypeID] FOREIGN KEY([TypeID])
REFERENCES [dbo].[Lookup] ([LookupID])
ALTER TABLE [dbo].[SampleCode] CHECK CONSTRAINT [FK_dbo.SampleCode_dbo.Lookup_TypeID]

ALTER TABLE [dbo].[SampleCode]  WITH CHECK ADD  CONSTRAINT [FK_dbo.SampleCode_dbo.User_AddedByUserID] FOREIGN KEY([AddedByUserID])
REFERENCES [dbo].[User] ([UserID])
ALTER TABLE [dbo].[SampleCode] CHECK CONSTRAINT [FK_dbo.SampleCode_dbo.User_AddedByUserID]

ALTER TABLE [dbo].[SampleCode]  WITH CHECK ADD  CONSTRAINT [FK_dbo.SampleCode_dbo.User_ChangedByUserID] FOREIGN KEY([ChangedByUserID])
REFERENCES [dbo].[User] ([UserID])
ALTER TABLE [dbo].[SampleCode] CHECK CONSTRAINT [FK_dbo.SampleCode_dbo.User_ChangedByUserID]

CREATE TABLE [dbo].[Lookup](
	[LookupID] [int] IDENTITY(1,1) NOT NULL,
	[LookupTypeID] [int] NOT NULL,
	[Abbreviation] [nchar](10) NULL,
	[LookupText] [nvarchar](50) NOT NULL,
	[AddedByUserID] [int] NOT NULL,
	[AddedDate] [datetime] NOT NULL,
	[ChangedByUserID] [int] NULL,
	[ChangedDate] [datetime] NULL,
 CONSTRAINT [PK_dbo.Lookup] PRIMARY KEY CLUSTERED 
(
	[LookupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[User](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nchar](10) NOT NULL,
	[Password] [nvarchar](14) NOT NULL,
	[Active] [bit] NOT NULL,
	[LastLogin] [datetime] NULL,
	[FirstName] [nvarchar](15) NOT NULL,
	[MiddleInitial] [nvarchar](5) NOT NULL,
	[LastName] [nvarchar](20) NOT NULL,
	[Phone] [nvarchar](12) NOT NULL,
	[PhoneExtension] [nvarchar](10) NOT NULL,
	[Cell] [nvarchar](12) NOT NULL,
	[Notes] [text] NOT NULL,
 CONSTRAINT [PK_dbo.User] PRIMARY KEY CLUSTERED

**Comment by akorchev** [comment]
Thank you for reporting this issue! Radzen incorrectly generates two properties with the same name in this case. We will fix this soon.

**Comment by akorchev** [comment]
The new version is now live - 1.0.4

**Comment by PETERHUP** [comment]
I can confirm that it is fixed and now works.
