### ISSUE TITLE
cannot connect to SQL Server 2008R2 on premises

### ISSUE THREAD

**Issue by x15041051** [akorchev/radzen#31]
Dear Atanas,
Thank you for the student licence for Radzen 1.0.3. 
The sample app works 100%.
But I cannot connect to SQL Server 2008R2 on premises. I keep getting "Inferring Schema" for hours.
kind regards
x15041051@student.ncirl.ie

**Comment by akorchev** [comment]
We have fixed a few SQL Server connectivity issues and will release a new version of Radzen later today (1.0.4). I will update this issue so you can check it out.

**Comment by x15041051** [comment]
Awesome! Thank you!

**Comment by akorchev** [comment]
The build is now live. Please reopen this issue in case the problem persists.
