### ISSUE TITLE
show style properties

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#35]
It would be nice to see style properties in the properties pane.  For example, if you resize a grid control in the designer, a height property is added to the screen meta json.  This generates a style attribute in the HTML which causes objects in subsequent rows to render on top of the grid rather tan beneath it.  

There is no way to remove the resize change in the designer.  If height or style property was displayed, we could remove the change.

Not sure if this might have something to do with styles hardcoded in the grid component(?).  It seems the grid renders 100% height even though the parent div has style="height:375", for example. 

Please let me know if this doesn't make sense.  I can provide repro steps.

**Comment by akorchev** [comment]
Yes, we need to fix that. Will update this issue once there is progress.

**Comment by akorchev** [comment]
We are about to start an overhaul of the existing visual design experience. This includes setting component style attributes apart from other things.
