### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by enchev** [akorchev/radzen#36]
Right now Radzen can connect to REST, OData and MS SQL Server. If there is interest we will add MySQL support as well. Add your (:+1:) reaction and/or comment.

**Comment by gmurimi** [comment]
Please add MySQL support

**Comment by akorchev** [comment]
We started working on adding MySQL support to Radzen. Stay tuned for updates.

**Comment by akorchev** [comment]
Radzen 1.6 just went live with support for MySQL!
