### ISSUE TITLE
Ability to reorder Navigation

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#38]
This would be nice.  I cannot seem to find a workaround. If I change the order in app.json, it renders in the new order in the designer, but doesn't render that way in the generated app.
Thanks in advance.

**Comment by akorchev** [comment]
@joshbooker pages should appear in the order they are in the `pages` array found in `app.json`.

**Comment by robertmclaws** [comment]
So I think the feedback on this is really two-fold. 

1) The designer should have a way to let you re-order the navigation without touching the app.json. 
2) The designer is honoring the order in app.json, but the generated app is not. Instead, the generator is ordering the pages alphabetically.

I am experiencing both of these issues myself:

**app.json:**
![image](https://user-images.githubusercontent.com/1657085/27745246-9a239558-5d90-11e7-9496-a80ac9033b68.png)

**app.conponent.html:**
![image](https://user-images.githubusercontent.com/1657085/27745216-820c6e9a-5d90-11e7-8a4b-a661f21f3c42.png)

HTH!

**Comment by joshbooker** [comment]
I too have found that the designer renders in the order of the navigation array in app.json, but they generate in the order of the pages array in app.json rather than the navigation array.

**Comment by joshbooker** [comment]
PS.. @robertmclaws what your take on status of OData .Net core support?
https://github.com/OData/WebApi/issues/1014

**Comment by robertmclaws** [comment]
@joshbooker I know it's coming. They are refactoring the entire stack, which takes time. I'm subscribed to every comment/checkin/whatever on the OData org, and they're getting up to 50-100 GitHub emails a day.

.NET Core is the future, so it's GOING to happen. And they're trying to make it happen soon. Just realize that now they have two frameworks that EVERYTHING has to support. Fortunately for us, .NET Standard 2.0 makes that a bit easier (most of the time). Anecdotally, I just ported a 37-project app to .NET Standard 2.0, and while it was a hassle, the benefits are massive.

So I'd say, just be patient. I know nothing about the schedule, and am not speaking for the team, but I'd expect to see something in the next 3 months. In the meantime, keep your APIs in separate projects on Legacy ASP.NET 4.6.2, and you should be fine.

HTH!
