### ISSUE TITLE
Connect to SQLEXPRESS

### ISSUE THREAD

**Issue by robhasos** [akorchev/radzen#39]
I've attempted to connect to a local SQLEXPRESS instance (.\SQLEXPRESS) and it can't connect. 

I've also tried adding the machine name (MACHINE-NAME\SQLEXPRESS)

The error is always that the machine address - . or MACHINE NAME can't be resolved.

**Comment by akorchev** [comment]
@robhasos could you try using `localhost\SQLEXPRESS` or just `localhost`?

**Comment by robhasos** [comment]
I've just tried them too and it's unable to connect. I assume this should work. I'm going to try on a different machine.

BTW I can send logs over if that helps.

**Comment by robhasos** [comment]
Having tried this on another machine, connection to the following all fail:
.\SQLEXPRESS
localhost\SQLEXPRESS
127.0.0.1\SQLEXPRESS
{MACHINE_NAME}\SQLEXPRESS

**Comment by akorchev** [comment]
@robhasos we would like to get to the bottom of this:

1. Are TCP connections enabled on this machine? Radzen needs TCP access to be enabled.
2. If you are running Radzen on a different PC the localhost connections won't work indeed - you may try by IP instead - <ip> or <ip>\SQLEXPRESS.
3. What version of SQL EXPRESS are you running?
4. Could it be that your firewall is blocking Radzen to connect to the port your SQL server is running?

You could send us a screenshot of your SQL TCP/IP configuration to info@radzen.com.

**Comment by akorchev** [comment]
@robhasos I have a hypothesis.  Could you check if SQL Browser service is running? If it isn't Radzen won't be able to connect to a SQL Express instance that uses dynamic ports. Other tools such as Visual Studio and Microsoft MSSQL Management Studio work because they read the port out of registry.

**Comment by robhasos** [comment]
SQL Browser was disabled. I’ve enabled it and get various different types of error:

localhost\sqlexpress

[cid:image001.png@01D2CA54.6A215A40]

. \sqlexpress

[cid:image002.png@01D2CA54.6A215A40]

ASGLH-WL-12148\SQLEXPRESS

[cid:image003.png@01D2CA54.7BFAE6F0]

I’m not sure where to find the TCP settings on SQLExpress

**Comment by akorchev** [comment]
@robhasos the SQL Express settings can be found in SQL Connection Manager. [Here](http://support.webecs.com/kb/a868/how-do-i-configure-sql-server-express-to-allow-remote-tcp-ip-connections-on-port-1433.aspx) is how to enable TCP/IP access. 

BTW the screenshots didn't make it through. You may have to upload them from github.com

**Comment by robhasos** [comment]
OK… the SQL Config Manager doesn’t appear on the start menu on my Win 10 machine but I found it via the MMC.

TCP/IP was disabled and that’s fixed it.

Localhost/SQLEXPRESS works but ./SQLEXPRESS doesn’t

**Comment by akorchev** [comment]
Yes. Using . won't work. We can probably support it though. However we cannot currently work without TCP/IP enabled because of the underlying technology we are using to connect to SQL server.

**Comment by robhasos** [comment]
No worries. Thanks for looking into it.

**Comment by akorchev** [comment]
We have updated the SQL documentation with a few [troubleshooting steps](http://www.radzen.com/documentation/ms-sql/#troubleshooting).
