### ISSUE TITLE
SQL Table called "System" results in build failure

### ISSUE THREAD

**Issue by robhasos** [akorchev/radzen#40]
I imported a database schema that contained a table called dbo.System. This resulted in the following build failure:

dotnet: Data\CatContext.cs(260,18): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]
Models\Cat\IntegrationFlow.cs(152,31): error CS0102: The type 'IntegrationFlow' already contains a definition for 'IntegrationService' [C:\dev\radzen\syscat\server\project.csproj]
Controllers\Cat\SystemsController.cs(27,24): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]
Controllers\Cat\SystemsController.cs(45,34): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]
Controllers\Cat\SystemsController.cs(73,34): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]
Controllers\Cat\SystemsController.cs(76,56): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]
Controllers\Cat\SystemsController.cs(91,58): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]

dotnet: Controllers\Cat\SystemsController.cs(105,34): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]
Controllers\Cat\SystemsController.cs(108,42): error CS0118: 'System' is a namespace but is used like a type [C:\dev\radzen\syscat\server\project.csproj]

**Comment by akorchev** [comment]
@robhasos reproduced. I guess we have to suffix tables that may end up as popular .NET namespaces.
