### ISSUE TITLE
Updating Tables in SQL Server Data Source Causes Errors

### ISSUE THREAD

**Issue by robhasos** [akorchev/radzen#41]
If I add all the tables from a database and generate some code, then decide to remove the screen and the underlying database table, errors are thrown.

For example, I initially added all tables, then decided to remove one. So I deleted the generated page and then went to update the database tables. I then got this on Running:
"The Cat data source does not have a getSystems operation"

When editing the data source, it needs to be possible to add and remove tables during development without throwing errors. It looks like the generator isn't cleanly removing entities when tables are removed.

**Comment by akorchev** [comment]
@robhasos will try to fix that.
