### ISSUE TITLE
Issue building (tied to issue 37)

### ISSUE THREAD

**Issue by carlosgjr** [akorchev/radzen#42]
Same issue with version 1.1.5
![radzen-issue-1](https://cloud.githubusercontent.com/assets/7093207/25948988/888dcaf8-361b-11e7-8e42-eca06bedd2a8.png)

**Comment by enchev** [comment]
Hey @carlosgjr,

Please try our latest Radzen 1.1.6 and let us know how it goes.

**Comment by carlosgjr** [comment]
issue fixed
