### ISSUE TITLE
Drop down lists not generating for all columns

### ISSUE THREAD

**Issue by carlosgjr** [akorchev/radzen#43]
Not all of the foreign key columns that should have a drop down list populated are being populated.

I see this issue across various tables.
![radzen-issue-3](https://cloud.githubusercontent.com/assets/7093207/26127492/27b6203a-3a4f-11e7-8263-399b82b7fd84.png)

**Comment by enchev** [comment]
Hey @carlosgjr,

We are working on this and I'll let you know immediately when the new version is ready!

**Comment by enchev** [comment]
Hi @carlosgjr,

We've just published our latest release and we believe that we've fixed this issue.

**Comment by carlosgjr** [comment]
issue has been addressed
