### ISSUE TITLE
Custom component sample?

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#45]
Any plans for a blog or sample code for registering custom components? Thanks.

**Comment by akorchev** [comment]
Will do. For now they would be used via the Html component (so no design time support). Will post updates in this issue.

**Comment by akorchev** [comment]
Just published a [how to document](http://www.radzen.com/documentation/custom-component/) that shows how to do it.

**Comment by joshbooker** [comment]
Super!  Thanks so much.  I assume one could have a template html file and use the templateUrl property in custom.component.ts.

'Component({
  selector: 'my-component',
  templateUrl: './custom.component.html'
})`

**Comment by akorchev** [comment]
Yes, `templateUrl` should work just fine. Angular CLI should pick it up and embed it properly in the final output.

**Comment by joshbooker** [comment]
Thanks for your reply.  

PS...how far out is ability to add user components to designer?  

Have you considered OSSing your radzen components so we can fork and load from our own repo? 

It may be nice to be able to add to AppImports in app.json > app.module-generated.ts

Thanks again!

**Comment by akorchev** [comment]
> PS...how far out is ability to add user components to designer?
Not so close unfortunately. A lot needs to be done before this is possible (better extensibility and some internal changes to allow that to happen). Definitely on our TODO list though! 

>Have you considered OSSing your radzen components so we can fork and load from our own repo?
Also in the plan. They are freely available in NPM right now but without the source code won't be of much use. Will discuss the options here.
> It may be nice to be able to add to AppImports in app.json > app.module-generated.ts
You can manually import stuff in app.module.ts and import it as well. For example:

```ts
import { SomeModule } from 'some-package';

@NgModule({
   imports: [
       SomeModule,
       ...AppImports
   ]
})

```
