### ISSUE TITLE
create REST from swagger

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#46]
After trying unsuccessfully to setup a REST datasource, I wonder if swagger import may be an option at some point.

**Comment by akorchev** [comment]
We have initial swagger support ready but isn't released officially yet. We plan to do so next week. If you are eager to try an internal build shoot an email to info@radzen.com and I will send you a link.

**Comment by joshbooker** [comment]
Thanks for your prompt reply.  I'm not that eager on a sunny Friday afternoon.  ;-)
Have a great weekend!

**Comment by akorchev** [comment]
We shipped initial Swagger support in 1.5 which is live now.

**Comment by joshbooker** [comment]
Just awesome community engagement.  Thanks!

A couple notes when adding swagger source:

1.  first page says 'Specify REST endpoint' instead of 'Swagger file path'
2.  on subsequent trips through the data source wizard, the endpoint url is saved rather than the swagger file path so you must choose the file again.
3.   would be nice to have ability to specify a url for swagger.json
4.  no ability to create pages for swagger entities (assume that coming later as this is prelim implementation)

Thanks again.  Keep up the great work!

**Comment by akorchev** [comment]
> first page says 'Specify REST endpoint' instead of 'Swagger file path'

The 'Specify REST endpoint' should accept both URL and path to a local file.

>on subsequent trips through the data source wizard, the endpoint url is saved rather than the swagger file path so you must choose the file again.

Because of it can be both. See my previous response.

> would be nice to have ability to specify a url for swagger.json

You should be able to do that now. Try pasting the URL. Or use the Sample swagger.

> no ability to create pages for swagger entities (assume that coming later as this is prelim implementation)

Yes. Swagger lacks one important bit that we need in order to allow the automatic CRUD page generation - the unique identifier of an entity. OData provides this information. What we plan to do is extend the "Create new page" dialog to support Swagger entities (it doesn't right now) and ask the user to specify which property of an entity is the unique id.

**Comment by joshbooker** [comment]
Thanks for your reply.  Let me try to clarify 1,2,3:

When I try to point to my swagger URL (which is default location for Swashbuckle enabled WebAPI)

https://northwindapi2.azurewebsites.net/swagger/docs/v1

Radzen hangs on 'inferring schema'.

If I download the file from the above URL and save it locally

C:\SOURCE\RadZen\NWSwagger\swagger.json

 its fine, but next time through it has the resource endpoint:

https://northwindapi2.azurewebsites.net/
 
which is neither the swagger URL nor the local swagger path.

**Comment by akorchev** [comment]
I see what you mean. Will fix that with the next build.

**Comment by joshbooker** [comment]
> Yes. Swagger lacks one important bit that we need in order to allow the automatic CRUD page generation - the unique identifier of an entity. OData provides this information. What we plan to do is extend the "Create new page" dialog to support Swagger entities (it doesn't right now) and ask the user to specify which property of an entity is the unique id.

Perhaps consider including the primary key assignment to the Edit Data Source 'wizard' so that it's applicable to REST endpoints as well.  This would allow all CRUD pages to be generated automatically similar to the SQL Server workflow. 

Also, it may be nice to see the results of swagger import shown in the Edit Data Source 'wizard' - as if swagger simply creates a REST datasource.  Then simply add a PrimaryKey checkbox on the Schema Properties and Operation Parameters arrays.

**Comment by akorchev** [comment]
That's a great idea!

**Comment by joshbooker** [comment]
PS...  Also consider Composite Keys, if possible.

**Comment by akorchev** [comment]
Swagger CRUD support shipped with 1.6.1!
