### ISSUE TITLE
How do we specify dotnet port for server backend?

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#48]
prolly some dotnet default setting somewhere but I cannot find it.  I need the client set to 5000 for cors reasons on another endpoint, but that's what dotnet is using so it breaks ng-cli listener.

TIA

**Comment by akorchev** [comment]
You can't right now. We will add support for the next version.

**Comment by akorchev** [comment]
Shipped with 1.5 today. Check the settings of the application (the '...'  button in the top right corner).
