### ISSUE TITLE
REST: OperationName must be unique

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#49]
I get a duplicate function error when operation name is not unique across all resources in a single REST connection.  I think even though it valid swagger, for this reason, it's fairly common for tooling to require unique operationIDs across all paths in a single swagger definition.

**Comment by akorchev** [comment]
Yep, makes sense. Although I have encountered at least one swagger DataSource that has duplicate operationId (or none whatsoever). Will support that in the next Radzen release.

**Comment by akorchev** [comment]
Implemented in 1.5 which we released earlier today.

**Comment by joshbooker** [comment]
Thanks!  I get the validation error for 'Operations must be unique' across all resources - as expected.

However, now I get 'Methods must be unique' across all resources too - not good!

**Comment by akorchev** [comment]
Will fix that in the next release!

**Comment by akorchev** [comment]
Should be fixed in 1.6

**Comment by joshbooker** [comment]
Method validation error is gone - as expected.  Thanks!

PS...

> Although I have encountered at least one swagger DataSource that has duplicate operationId (or none whatsoever)

This is another good reason for Swagger option to create a REST Connection that is editable in the same way a scratch REST connection is editable.  

https://github.com/akorchev/radzen/issues/46#issuecomment-306259435

The users could correct non-unique operation, assign Primary and foreign keys, etc. Even though that info may not be in the original swagger file.  Basically, it will allow users to fill in the blanks.
