### ISSUE TITLE
Deploy to IIS

### ISSUE THREAD

**Issue by leam77** [akorchev/radzen#50]
Hello, I am stuck at step 4 of the documentation to Deploy to IIS (Copy the contents of the server\bin\Release\netcoreapp1.1\publish directory to your server). Could you please be more specific? Where exactly in the directory structure of the published website should I copy the content?  I have the Radzen App running at an Azure website but can not execute CRUD operation due to the lack of configuration with the Azure MS SQL Server Data Source. I think this is the last issue I need to solve to start developing with Radzen.  A walkthrough will be great. Excellent job!

**Comment by akorchev** [comment]
You need to copy the contents of the `publish` directory to your web server - in the root of the virtual directory. For example you can create a virtual directory in `c:\website\radzen-app`. Then you should copy the files there.

>  I have the Radzen App running at an Azure website but can not execute CRUD operation due to the lack of configuration with the Azure MS SQL Server Data Source

Couldn't understand that one. Could you elaborate?

**Comment by leam77** [comment]
Thank you, I will keep trying. Please look at [http://buhuru3.azurewebsites.net] and add a record to check what I meant.

**Comment by akorchev** [comment]
That site tries to connect to `http://localhost:5000`. You should change the data source endpoint for production. Check the [Change production endpoints section](http://www.radzen.com/documentation/deploy/):

> Sometimes you would like to use a different REST/OData service URL in production. To do so update `src/environments/environment.prod.ts` - replace the URL of your services with the new ones.

**Comment by leam77** [comment]
This is what I have at environment.prod.ts:

export const environment = {
  buhuru: 'http://localhost:5000/odata/BUHURU',
  production: true
};

I am not using odata, I am using  MS SQL Server Data Source.  What connection string I have to set?

**Comment by akorchev** [comment]
1. First you have to deploy the .NET Core application to Azure e.g. `buhuru4.azurewebsites.net`. 

Probably the easiest way is via [OneDrive](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-deploy-content-sync).

2. Then set `buhuru` to `http://buhuru4.azurewebsites.net/odata` in environment.prod.ts and rebuild via `ng build -prod`

To set the connection string for the .NET Core application you should set it as an app setting variable: https://stackoverflow.com/a/34622196/10141. Use the same key as in the deployment documentation e.g. `ConnectionStrings:BuhuruConnection`

BTW we will increase the priority of the deployment feature of Radzen.

**Comment by leam77** [comment]
Thank you but it is not working for me. Is there a way to schedule a remote assistance?

**Comment by akorchev** [comment]
> Thank you but it is not working for me

What part is not working for you? Deploying the .NET Core application to Azure? Or changing the service URL in the Angular application (still looking for localhost:5000)?

> Is there a way to schedule a remote assistance?

We can probably schedule a skype call or something similar. Shoot an email to info@radzen.com.

**Comment by akorchev** [comment]
We started work on the deployment feature! IIS and Azure deployment are coming.

**Comment by leam77** [comment]
Great, thanks.

**Comment by enchev** [comment]
[Radzen 1.7](download.radzen.com) is live with support for IIS and we will release soon [FTP/Azure deploy](https://twitter.com/vladimir_enchev/status/879685298271244288) support.
