### ISSUE TITLE
Radzen/LightSwitch - CRUD

### ISSUE THREAD

**Issue by ethnoplex** [akorchev/radzen#51]
Maybe somebody is interested in Radzen on a LightSwitch service, so I wanted to share my experiences so far:

- Create a little sample database [RZLS] on SQL-Server:

```
USE [RZLS]
GO
/****** Object:  Table [dbo].[CUSTOMERS]    Script Date: 07.06.2017 09:22:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMERS](
	[ID] [uniqueidentifier] NOT NULL,
	[SEARCH_TERM] [nvarchar](max) NOT NULL,
	[CUSTOMER_NUMBER] [int] NOT NULL,
	[NAME] [nvarchar](max) NULL,
	[STREET] [nvarchar](max) NULL,
	[ZIP_CODE] [nvarchar](max) NULL,
	[CITY] [nvarchar](max) NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 07.06.2017 09:22:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[ID] [uniqueidentifier] NOT NULL,
	[AMOUNT] [money] NOT NULL,
	[CUSTOMER_ID] [uniqueidentifier] NOT NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
 CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
INSERT [dbo].[CUSTOMERS] ([ID], [SEARCH_TERM], [CUSTOMER_NUMBER], [NAME], [STREET], [ZIP_CODE], [CITY]) VALUES (N'2a9e0726-cc4a-e711-87a6-080027d98072', N'Customer 1', 100, N'Customer 1 Corp.', N'Oneroad', N'1001', N'Firstvillage')
GO
INSERT [dbo].[CUSTOMERS] ([ID], [SEARCH_TERM], [CUSTOMER_NUMBER], [NAME], [STREET], [ZIP_CODE], [CITY]) VALUES (N'ddb19038-cc4a-e711-87a6-080027d98072', N'Customer 2', 101, N'Customer 2 Inc.', N'Twostreet', N'1002', N'Secondtown')
GO
INSERT [dbo].[ORDERS] ([ID], [AMOUNT], [CUSTOMER_ID], [DESCRIPTION]) VALUES (N'ed04d7c8-cc4a-e711-87a6-080027d98072', 1100.0100, N'2a9e0726-cc4a-e711-87a6-080027d98072', N'Initial')
GO
INSERT [dbo].[ORDERS] ([ID], [AMOUNT], [CUSTOMER_ID], [DESCRIPTION]) VALUES (N'5ba272cf-cc4a-e711-87a6-080027d98072', 1200.0200, N'ddb19038-cc4a-e711-87a6-080027d98072', N'Successor')
GO
ALTER TABLE [dbo].[CUSTOMERS] ADD  CONSTRAINT [DF_CUSTOMER_ID]  DEFAULT (newsequentialid()) FOR [ID]
GO
ALTER TABLE [dbo].[ORDERS] ADD  CONSTRAINT [DF_TASK_ID]  DEFAULT (newsequentialid()) FOR [ID]
GO
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_CUSTOMERS] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMERS] ([ID])
GO
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_ORDERS_CUSTOMERS]
GO
```

- Create a new LightSwitch Web application and add [RZLS] as a „Data Source“ to the server project. This should lead to:

![rzls_datasource](https://user-images.githubusercontent.com/29063783/26969232-52702f1e-4d05-11e7-90d6-d652b5806fca.png)

- Add a „Global.asax“ to the server project and replace  the function „Application_BeginRequest“ for CORS:

```
protected void Application_BeginRequest(object sender, EventArgs e)
{
	var res = HttpContext.Current.Response;
	var req = HttpContext.Current.Request;
	res.AppendHeader("Access-Control-Allow-Origin", (req.Headers["Origin"] == null ? "*" : req.Headers["Origin"]));
	res.AppendHeader("Access-Control-Allow-Credentials", "true");
	res.AppendHeader("Access-Control-Allow-Headers", "Content-Type, X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Date, X-Api-Version, X-File-Name, MaxDataServiceVersion, DataServiceVersion, If-Match, Authorization");
	res.AppendHeader("Access-Control-Allow-Methods", "POST,GET,PUT,PATCH,DELETE,OPTIONS");

	// ==== Respond to the OPTIONS verb =====
	if (req.HttpMethod == "OPTIONS")
	{
		res.StatusCode = 200;
		res.End();
	}
}
```

- Read the following, if you want to access the LS service from an external device while executing from Visual Studio. **You have to run VS as administrator to make that work.** You could also use a wildcard for the external IP within the attribute: _bindingInformation="\*:[YOUR_PORT]:\*"_

[IIS Express from remote](http://johan.driessen.se/posts/Accessing-an-IIS-Express-site-from-a-remote-computer)

- Start your LightSwitch Web application from Visual Studio and try to query the service in Fiddler or Postman: _http://[YOUR_HOST]:[YOUR_PORT]/RZLSData.svc/$metadata_

- Hope this worked. Time for the incredible Radzen! Within Radzen, create a new application and add a new datasource named „rzls“ with your endpoint at: _http://[YOUR_HOST]:[YOUR_PORT]/RZLSData.svc_. Select „Generate pages for CRUD operations“ and deselect the empty namespace including the „Error“ entity:

![rzls_odata](https://user-images.githubusercontent.com/29063783/26972852-cc1d37f4-4d13-11e7-80c6-a0a084f488ca.png)

- Finish the wizard and set the newly created „ORDERS“ page as the start page. Next, run and enjoy your application:

![data](https://user-images.githubusercontent.com/29063783/26973861-cd12df06-4d18-11e7-9ef6-72cd9c8bdf1b.png)

- Still interested? Let's get into some details - Radzen normally detects relationships on datasources reliably. However the LS service is a little bit rebellious. An experienced LightSwitcher knows how to deal with *.lsml files. Radzen provides something similar if you explore the „meta“ directory of the project folder.  I'm not sure if the following replacements are really necessary, but it seems neater.  So, please open the „meta/data/rzls.json“ file and search for the „CUSTOMER_ID“ property definition of the „LightSwitchApplication.ORDER“ entity. Then replace the definition by the code listet below - it should construct our _ORDER to CUSTOMER_ relationship:

```
"CUSTOMER_ID": {
  "format": "uuid",
  "type": "string",
  "x-foreignKey": {
    "name": "Customer",
    "parentTable": "LightSwitchApplication.CUSTOMER",
    "principalKey": "ID",
    "textProperty": "SEARCH_TERM",
    "type": "CUSTOMER"
  },
  "x-key": false
},
```

- Replace the ID definition of „LightSwitchApplication.CUSTOMER“ for the _CUSTOMER to ORDERS_ relationship too.

```
"ID": {
  "format": "uuid",
  "type": "string",
  "x-key": true,
  "x-navigation": [
    {
      "inversePropertyName": "CUSTOMERS",
      "name": "Orders",
      "type": "ORDER"
    }
  ]
},
```

- Now we want to show the related customer in the orders list.

1. Open the „ORDERS“ page. We need to expand the customer entity of the order entities when the DataGrid is loaded. Therefore we add the „$expand“ parameter in „_LoadData -> rzls.getORDERS -> Parameters_“. Enter „CUSTOMER“ in the value field. 

2. Select the DataGrid and add a new column. Enter „CUSTOMER_ID“ into the property field and „${data.CUSTOMER?.NAME}“ into the template field.

3. Switch to the DataGrid „Events“ tab and fill the „$expand“ parameter according to the first step. This is needed for reloads.

4. Remove, reorder and format the columns as you like.

![template_expand](https://user-images.githubusercontent.com/29063783/26985857-a5f4a04e-4d45-11e7-9eb0-8ce340fa0820.png)

- You've probably clicked on the orders list and wondered about the empty dialog. This is because the sample database inconveniently uses Guids for primary keys. So, we have to modify the communication between our application and LightSwitch without touching the Radzen generated Angular service. While we're on it, let's fix some more of the LS oddities with a quick and dirty hack. Most of it is self-explanatory, i think:

1. Create the file „httpls.service.ts“ in the „client/src/app“ folder and paste this:

```
import { Injectable } from '@angular/core';
import { Http, XHRBackend, RequestOptions, Request, RequestOptionsArgs, Response, Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { environment } from '../environments/environment';

// LightSwitch service expects the prefix 'guid' on guid keys
const guidUrl = (url: String): string => (
  url.toString().replace(/'[0-9a-f]{8}-[0-9a-f]{4}/i, "guid$&")
);

@Injectable()
export class HttpLs extends Http {
  request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {
    if (options) {
      //options.headers.append("Authorization", `Basic ${btoa("[YOUR_USER]:[YOUR_PASSWORD]")}`);  
      switch(options.method) {
        case "get": {
          url = guidUrl(url.toString());
          
          let search = <URLSearchParams>options.search;
          if (search) {
            // rewrite string filter for LightSwitch service
            let filter = search.get("$filter");
            if (filter) {
              filter = filter.replace(/contains\((.+?), (.+?)\)/g, "substringof($2, $1) eq true");
              search.set("$filter", filter);
            }
          }
          break;
        }
        case "patch":
        case "delete": {
          url = guidUrl(url.toString());
          // LightSwitch service expects If-Match on update and delete - there is no "etag" in the entity on get.
          options.headers.append("If-Match", "*");
          break;
        }
        case "post": {
          // modify for different key types
          let body = options.body;
          if (body) {
            let uuid = require("uuid");
            let bodyObj = JSON.parse(body);
            bodyObj["ID"] = uuid.v4();

            // LightSwitch service expects the Decimal type as string. Other numeric types seem to also work as string.
            options.body = JSON.stringify(bodyObj, (key, value) => {
              if (typeof value === "number") {
                return value.toString();
              }
              return value
            });
          }
        }
      }
    }

    return super.request(url, options);
  }
}
```

2. Override the application-wide http service by modifying „app.module.ts“ to:

```
import { NgModule } from '@angular/core';

import { AppImports, AppComponent, AppDeclarations, AppProviders } from './app.module-generated';

import { Http, HttpModule, RequestOptions, XHRBackend } from '@angular/http';
import { HttpLs } from './httpls.service';

export function httpLsFactory(backend: XHRBackend, options: RequestOptions) {
  return new HttpLs(backend, options);
}

@NgModule({
  declarations: [
    ...AppDeclarations
  ],
  imports: [
    ...AppImports
  ],
  providers: [
    ...AppProviders,
    {
      provide: Http,
      useFactory: httpLsFactory,
      deps: [XHRBackend, RequestOptions]
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```
- Finally, a customer lookup for the order dialog would be great. Thus open the „Edit ORDER“ page in Radzen and select the form. Create a new field by clicking plus on the fields section header and scroll down to the new entry. For me it was useful to start with the title, because sometimes it looks like the field is missing in the designer.

1. Set „Title“ to „CUSTOMER“
2. Set „Type“ to „lookup“
3. Select „CUSTOMER_ID“ from the „Property“ dropdown
4. Select „SEARCH_TERM“ from the „TextProperty“ dropdown
5. Select „ID“ from the „ValueProperty“ dropdown
6. Type „Choose Customer“ into „Placeholder“

![lookup](https://user-images.githubusercontent.com/29063783/26991095-5643f55e-4d59-11e7-9ed8-8d520441a126.png)

- Repeat the previous procedure for the „Add ORDER“ page as well. But you have to type „CUSTOMER_ID“ manually into the „Property“ dropdown. Afterwards remove and reorder the fields as you like. 

![final](https://user-images.githubusercontent.com/29063783/26995433-dea8bc64-4d6c-11e7-9335-0427372dc950.png)

- Last but not least, this post is only for demonstration purposes - pick the useful parts. Let there be light and switch to Radzen! :+1:

Best wishes,
Michael

PS: +1 Radzen Developer Community :smile:

**Comment by leam77** [comment]
Thanks as always Michael, glad of having you here. I am getting TypeError: Cannot read property 'then' of undefined, when trying to create the Odata source at Radzen. The code at Global.asax looks fine. What do you think I am doing wrong?

**Comment by ethnoplex** [comment]
Hi leam77,

I’m not Michael Washington - we all deeply respect Michael for his outstanding work in the LightSwitch community. It would be great to see an icon like him as a member of the Radzen developer community.

I think you tried to use _http://[YOUR_HOST]:[YOUR_PORT]/RZLSData.svc/$metadata_ as the endpoint.

_http://[YOUR_HOST]:[YOUR_PORT]/RZLSData.svc_ should work.

**Comment by leam77** [comment]
It works! Thanks. How can I secure the data source? If SharePoint enabled, what ClientID and Authorization URL has to be used?

**Comment by ethnoplex** [comment]
> ... How can I secure the data source? ...

I’ve updated the post. LightSwitch only provides Windows and Form authentication by default. Add „Authorization“ to the „Access-Control-Allow-Headers“ in „Global.asax“ and find the following line in „httpls.service.ts“.

```
//options.headers.append("Authorization", `Basic ${btoa("[YOUR_USER]:[YOUR_PASSWORD]")}`);
```

 > ... when editing/deleting a record I get this error ...

_options.headers.append("If-Match", "*");_ in „httpls.service.ts“ should exactly handle that. [see](http://wijmo.com/topic/only-if-match-headers-are-supported-for-updatedelete-operations/)

**Comment by joshbooker** [comment]
nice post.  In the absence of and official Radzen community forms, perhaps @akorchev should add a 'Community' & 'Discussion' labels.

**Comment by joshbooker** [comment]
Your relationship fix (swapping x-foreignkey with x-navigation) is neat.  The problem isn't really a LightSwitch thing per-se.  It's a WebAPI\OData v3 limitation.  V3 metadata only exposes uni-directional associations, while v4 improved this with bi-directional navigation properties.  
More info:
https://d-fens.ch/2014/07/27/webapi-odata-v3-can-only-generate-uni-directional-associations/
which I believe is actually caused by WebAPI OData mutiplicity issue:
https://github.com/OData/WebApi/issues/27
Ironically, the above work issue from a couple years back was updated only 6 days ago.  With any luck, the OData team is gonna restart long awaited forward momentum.

**Comment by joshbooker** [comment]
@ethnoplex did you find RadZen wasn't adding the If-Match header?  I thought I read that was added here:
https://github.com/akorchev/radzen/issues/18

**Comment by akorchev** [comment]
Radzen uses If-Match only if the entity has `@odata.etag` https://github.com/akorchev/radzen/blob/master/demos/odata/client/src/app/sample.service.ts#L149

I guess for OData v3 we have to set it always.

**Comment by akorchev** [comment]
@joshbooker created those labels. We are also investigating possible options for a forum. Currently wandering if we should pick a traditional forum or the Q & A solutions that are getting popular (similar to stackoverflow). Thoughts?

**Comment by fileman** [comment]
why not use stackoverflow with [Radzen] tag?

**Comment by ethnoplex** [comment]
**@joshbooker:** Thank you for the information. To be honest, I copied and adapted the meta from a MSSQL/OData v4 Radzen project. You’re right, several issues are related to OData v3, but I did not want to scare some LS users. I think the Radzen team will extend the v3 support in the future, so that you don’t have to override the Http class.

The post should show the flexibility of Radzen and the underlying technology in a practical example. I enjoyed your conversation with Mike-EEE and the “RadZen under the covers” post. Furthermore, I share your opinion:

> “At this point, I believe, if more LS devs got onboard with Radzen, we could provide feedback to make it exactly what we want and my experience with the creators makes me believe they'd be both willing and grateful.”

**Comment by joshbooker** [comment]
> We are also investigating possible options for a forum. Currently wandering if we should pick a traditional forum or the Q & A solutions that are getting popular (similar to stackoverflow). Thoughts?

I'm more of a traditional forums kinda guy - not a huge fan of the new chat-style support such a gitter.  I find a well moderated forum is useful for searching previously solved problems whereas gitter-style is not.  The former lends to a nice knowledge base and community involvement while the latter is a bunch of 'one-offs' and little camaraderie.

Also not a big fan of SO.  I find the moderators spend too much time rejecting questions - but that's just me.  If you build it, whatever it is, we will come.

Honestly, I see nothing wrong with this github format as long as it doesn't clutter your work items.

**Comment by akorchev** [comment]
@enchev and I discussed things and decided we should probably stick with Github issues for a little longer. We know it is not ideal but would give us more time to work on features. Maintaining both GH issues and a forum would be a drag.

**Comment by ethnoplex** [comment]
Thanks for the info. Searching the repository for previously solved problems seems to work and the labels are helpful.  I'm fine with it.

**Comment by akorchev** [comment]
@ethnoplex we put some more thinking and may reconsider after all. Having discussions in github issues is not ideal. It is perfect for issues, feature requests and such but not so much for chatting, sharing solutions and helping each other. Will try to set something up when time permits.

**Comment by akorchev** [comment]
FWIW we've launched a forum. Check it out at http://forum.radzen.com

**Comment by enchev** [comment]
Hey folks,

We are happy to announce that with just released Radzen 1.11 consuming LightSwitch services is a lot more easier:
https://www.radzen.com/documentation/migrating-from-lightswitch/

**Comment by ethnoplex** [comment]
@enchev and @akorchev - That is great news, thank you so much for your service and support!

**Comment by leam77** [comment]
Thank you for making consuming LightSwitch services easier. When crearting a new record I am getting this error:

{"odata.error":{"code":"1","message":{"lang":"en-US","value":"<?xml version=\"1.0\" encoding=\"utf-16\"?><ExceptionInfo><Message>If-Match or If-None-Match HTTP headers cannot be specified for POST operations.</Message></ExceptionInfo>"}}}

also, when deleting:

{"odata.error":{"code":"1","message":{"lang":"en-US","value":"<?xml version=\"1.0\" encoding=\"utf-16\"?><ExceptionInfo><Message>Only 'If-Match' headers are supported for Update/Delete operations.</Message></ExceptionInfo>"}}}

CORS compatibility looks fine and the endpoint seems correct due to it was automatically generated as:

export const environment = {
  radZen1: 'https://xxxxx.azurewebsites.net/ApplicationData.svc/',
  production: true
};

Sincerely,

**Comment by akorchev** [comment]
@leam77 is this OData service v3 or v4? Currently we are adding the If-Match header only for v3.

> {"odata.error":{"code":"1","message":{"lang":"en-US","value":"Only 'If-Match' headers are supported for Update/Delete operations."}}}

What are the other headers sent during DELETE request? I wonder if it is the `accept` header or something else. 

How was this OData service created? We would like to test locally and fix the incompatibilities.

**Comment by enchev** [comment]
Hi @leam77,

We believe that we have fix for these problems already. Please ping us at info@radzen.com for new version.

**Comment by leam77** [comment]
Thanks both, I am using Radzen version 1.11.0 and just folowing the documentation guide by consuming data from existing LightSwitch application. So I suppose it is OData v3.

**Comment by akorchev** [comment]
@leam77 we have reproduced those issues and have fixed it. The fix will be part of the next release. However we can provide a private hotfix should you need it earlier.

**Comment by enchev** [comment]
@leam77 Radzen version 1.11.1 is already live. Please let us know if you still have any problems!

**Comment by leam77** [comment]
It is perfectly working. Thanks!

**Comment by enchev** [comment]
Great! I'm closing this for now. If you have any other questions and/or problems related to LightSwitch please let us know!
