### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by Ox29A** [akorchev/radzen#52]
I have Microsoft Sql Server Management studio 2017 installed on my machine and i can't seem to connect to my local database instace SQLExpress, i have enabled SQL authentication, but it's not letting me connect within radzen, i have no issues connecting from inside MSSMS, 

Any Ideas?

Kind Regards, 

Corey.

**Comment by akorchev** [comment]
Please check the [troubleshooting](http://www.radzen.com/documentation/ms-sql/#troubleshooting) instructions.
