### ISSUE TITLE
Time options for DateTime fields

### ISSUE THREAD

**Issue by robertmclaws** [akorchev/radzen#55]
I'm working on a Time Tracking application, and I have my time entries backed by a DateTime field. Radzen does a great job of having controls for date, but it would be great to have a configurable time picker as well.

It would also be great if you could pick date and time in the same popup control.

Thanks!

**Comment by enchev** [comment]
Hey @robertmclaws,

It will be available in the next version of Radzen, I'll let you know when the build is ready!
