### ISSUE TITLE
Group Layout control suggestion

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#56]
Thanks for the [roadmap](http://forum.radzen.com/t/radzen-roadmap/26/4). 
Just a suggestion for layouts...

Consider a Group Layout control which is a container for child controls. The group can be configured to render children responsively in either columns or rows. Group controls can be nested so any layout can be achieved with ease.

 For example:
>RowsLayout
>>ColumnsLayout
>>>RowsLayout:column1
>>>>Field1
>>>>Field2

>>>RowsLayout:column2
>>>>Field3
>>>>Field4

>>>RowsLayout:column3
>>>>Field5
>>>>Field6

>>RowsLayout:ComandBar
>>>ColumnsLayout
>>>>SubmitButton
>>>>CancelButton

Renders a page with three columns of fields and a row of buttons in the footer. 

| column1 | column2 | column3 |
|---|---|---|
| Field1 | Field3 | Field5 |
| Field2 | Field4 | Field6 |

|---- Submit ----|---- Cancel ----|
|---|---|

The simplicity of this one group control is something that made the designtime experience of LightSwitch very intuitive yet powerful. 
Keep up the great work.

**Comment by akorchev** [comment]
For now we are lining in favor of bootstrap rows and columns. We plan to allow arbitrary nesting of rows and columns which should make such scenarios possible.
