### ISSUE TITLE
Unable to complete "Consume REST service" Guide due to unable to look up to ${result.albums.items}

### ISSUE THREAD

**Issue by primegnome** [akorchev/radzen#58]
First I would like to say this is a great tool!

I tried to use the trial version 1.8.0, following the "Consume REST service" guide step by step, but without success. Thus I checkout from the repo here and tried to do some comparison on the generated meta data, here is the findings:
- In git repo, which is working, the generated Spotify.json has the reference defined, for instance:
        "artists": {
          "type": "array",
	  "items":{
		"$ref": "#/definitions/Artist"
		}
        },
    "AlbumsResponse": {
      "properties": {
        "albums": {
		"$ref": "#/definitions/Albums"
        }
      }
    },

- while with the latest version (1.8.0 or 1.8.1), below is generated (refer to Spotify3.json)
"artists": {
          "array": true,
          "format": null,
          "type": "Artist"
        },
       "AlbumsResponse": {
      "properties": {
        "albums": {
          "format": null,
          "type": "Albums"
        }
      }
    },

With Spotify3.json, which is generated by latest version 1.8.0/1.8.1, when I tried to set the page property in page events -> Then handler -> set property with name=releases, the value I cannot set to ${result.albums.items}, Radzen only managed to lookup to ${result.albums}.  this leads to bind fail and not able to set the data property of data-grid. 

While with Spotify.json, it works ok. 

Appreciated your help!

[Spotify - working.json.txt](https://github.com/akorchev/radzen/files/1120929/Spotify.-.working.json.txt)
[Spotify3.json.txt](https://github.com/akorchev/radzen/files/1120930/Spotify3.json.txt)

**Comment by akorchev** [comment]
Unfortunately this seem to be a regression bug. Indeed the data source references are not properly set. We will update the issue once this bug is fixed.

**Comment by enchev** [comment]
Fix for this issue is included in recently released Radzen 1.9.0
