### ISSUE TITLE
OData v4 "ID" endpoint incorrect

### ISSUE THREAD

**Issue by robertmclaws** [akorchev/radzen#60]
In Radzen 1.8.2, I just regenerated an OData source that had changed under the covers. When I did, it started wrapping the ID in single quotes.
Ex: `http://localhost:42111/v1/Projects('79a33fba-e3e8-456e-81b4-a8ff5e448218')`
OData V4 GUID IDs are not supposed to be quoted.
Ex: `http://localhost:42111/v1/Projects(79a33fba-e3e8-456e-81b4-a8ff5e448218)`

Fortunately, the format was specified in the generated JSON file, so all I had to do was a quick find-and-replace.

But I thought you should know. Thanks!

**Comment by fileman** [comment]
Hi Robert,
like you've said OData doesn't require quotes, but RESTier use GUID with quotes!
I think is better to have documentation to customize this instead of have GUID quoted or dont quoted

**Comment by robertmclaws** [comment]
Actually, RESTier is the framework I'm using and it doesn't require quotes either. It conforms to the OData v4 spec.

**Comment by fileman** [comment]
Have you fixed in your "AdvancedREI" version or you have more recent commit?
see [RESTier#547](https://github.com/OData/RESTier/issues/547)

**Comment by robertmclaws** [comment]
Microsoft fixed it in Restier already for RTM, and my fork ships with the fix.

**Comment by enchev** [comment]
Hi @robertmclaws,

We have internal data-base (with GUID) for tests purposes for our own OData services (V4) used to expose MS SQL Server data and there are no quotes:
![image](https://user-images.githubusercontent.com/5804953/28167513-80bdd052-67e4-11e7-8f04-9cea5b71635e.png)
![image](https://user-images.githubusercontent.com/5804953/28167522-8c4cdc7e-67e4-11e7-9ba0-74dc1d635ff8.png)
![image](https://user-images.githubusercontent.com/5804953/28167527-909635fa-67e4-11e7-8028-ca104db30a5a.png)

Maybe in your case the type is string?

**Comment by robertmclaws** [comment]
Is that a Restier-based service or just a regular WebAPI service? I'm using Restier, but a fork I'm shipping that has their changes since the last beta.

I just had Radzen re-generate the API, and once again it had quotes around the IDs. I had to remove them manually.

![image](https://user-images.githubusercontent.com/1657085/28177459-dcf3fe08-67c8-11e7-992b-1395a28c98c8.png)

**Comment by enchev** [comment]
Just plain WebAPI/OData service

**Comment by akorchev** [comment]
@robertmclaws are the quotes appearing in the data source's JSON file? Is that where you are removing them from? Can you paste here the whole XML from the metadata? We can test locally with it.
