### ISSUE TITLE
Specifying Complex Dropdown TextProperty Values

### ISSUE THREAD

**Issue by robertmclaws** [akorchev/radzen#61]
So I have an app that is using an OData API. One of the tables it accesses connects the concept of a "project" with the concept of a "User", and had properties that relate back to said tables.

The "edit" page properly generates a dropdown for me. I was also able to edit the query feeding that dropdown so that the User and Project properties are expanded. What I can't figure out is, how to specify multiple properties for binding, so I can achieve the equivalent of `Project.DisplayName + " | " + User.LastName` (or `MyProject | McLaws`) as the displayed information for the dropdown.

If that is already possible, any assistance you could provide would be appreciated. If it's not, having that feature would be awesome 😄. Thanks!

**Comment by akorchev** [comment]
Hi @robertmclaws !

No, this behavior isn't supported at the moment. It is however something we can easily add. Will follow up when we ship it!

**Comment by akorchev** [comment]
The DropDown component now has a Template property which allows for such customizations.
