### ISSUE TITLE
Deploy Error with security

### ISSUE THREAD

**Issue by codernz** [akorchev/radzen#69]
radzen: Generating code ...
radzen: Code generation done in 321ms.
radzen: Preparing server application for publish ...
dotnet:  
Restoring packages ...
dotnet:   Restore completed in 196.6 ms for C:\data\Clients\App\server\project.csproj.

dotnet:   Restore completed in 386.35 ms for C:\data\Clients\App\server\project.csproj.

dotnet: Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

dotnet:   project -> C:\data\Clients\App\server\bin\Release\netcoreapp1.1\server.dll

radzen: Server application prepare for publish done in 5692ms.
radzen: Building Angular application in production ...
dotnet:   
project -> C:\data\Clients\App\server\bin\Release\netcoreapp1.1\publish\

ng-cli: Date: 2017-12-12T17:10:09.474Z
Hash: 583df00233ad16c26b5a
Time: 26939ms
chunk {0} polyfills.b8e413aba154a056f255.bundle.js 
(polyfills) 97.3 kB {4} [initial] [rendered]
chunk {1} main.372100323848c378f90a.bundle.js (main) 411 bytes {3} [initial] [rendered]
chunk {2} 
styles.4918708b2b64fc5d0ec8.bundle.css (styles) 403 kB {4} [initial] [rendered]
chunk {3} vendor.8a982f96e0099448579b.bundle.js (vendor) 210 kB [initial] [rendered]
chunk {4} inline.e99a49a88a20567f020c.bundle.js (inline) 1.45 kB [entry] [rendered]

ng-cli: 
ERROR in Cannot determine the module for class UnauthorizedComponent in C:/data/Clients/Murray/Web/Mitre10/client/src/app/unauthorized.component.ts! Add UnauthorizedComponent to the NgModule to fix it.
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\data\Clients\App\client\src'
resolve './$$_gendir/app/app.module.ngfactory' in 'C:\data\Clients\App\client\src'
  using description file: C:\data\Clients\App\client\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\data\Clients\App\client\package.json (relative path: ./src)
    using description file: C:\data\Clients\App\client\package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory.js doesn't exist
      as directory
        C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory doesn't exist
[C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory]
[C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory.ts]
[C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory.js]
[C:\data\Clients\App\client\src\$$_gendir\app\app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

ng-cli: Exited with code: 1
radzen: undefined

**Comment by akorchev** [comment]
Damn. Could you please try the following?

1. Delete the src/app/unauthorized.component.ts file.
2. In Radzen go to **security** and click the **Save** button.
3. Run the application.

**Comment by codernz** [comment]
Thanks its now deploying

**Comment by enchev** [comment]
Radzen 1.24.1 was just released with fix for this problem included!
