### ISSUE TITLE
Error When Trying To Import SQL Server Schema

### ISSUE THREAD

**Issue by NimbusHex** [akorchev/radzen#73]
Getting an error of:
"TypeError: Cannot set property 'MainSize' of null" when trying to import the schema of our database.  I'm sure it's likely due to the shoddy nature of our database structure, and I am able to import smaller databases, but some hints on the specific problem would be greatly appreciated.  Attached is the diagnostic log file.

Thank you!

[log.txt](https://github.com/akorchev/radzen/files/1679240/log.txt)

**Comment by akorchev** [comment]
Hi @NimbusHex ! Is there any chance to send us an SQL DB create script of your database to info@radzen.com? We don't need the data - only the DB schema. Once we have it we will troubleshoot the import issue and fix it.

**Comment by NimbusHex** [comment]
Will do, trying to narrow down what specifically in the database is causing it, because when I create a new database with just the tables (no views, stored procedures, etc), it is able to import the schema just fine.  Thank you very much for the quick response.

**Comment by akorchev** [comment]
@NimbusHex ok. If you can't find it feel free to send us the db script. We can reproduce it immediately once we have it.
