### ISSUE TITLE
Ability to cancel when editing handlers

### ISSUE THREAD

**Issue by ielbury** [akorchev/radzen#75]
There needs to be a Cancel in addition to the Done button in specific when editing handlers. 

If I am experimenting, I need to remember what the handler was before I start so that I can reset the changes I have made. I realize the "current" idioms are to always save, but there is a case to be made that there are times where an interaction is transactional.

**Comment by akorchev** [comment]
Hi. This sounds reasonable and we have logged it in our TODO list.

**Comment by akorchev** [comment]
Implemented in latest Radzen.
