### ISSUE TITLE
CRMDemo SQL compatibility

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#78]
Nice demo!

The following script will only run without error on SQL 2016:
https://github.com/akorchev/radzen/blob/master/CRMDemo/mssql-db.sql

suggest you comment out a few lines as seen here:
https://github.com/joshbooker/CRMDemo/commit/2317db4ef4d4703a2250458d5028629ad68e3930#diff-7470c8057f17b0b9e5a7de1702b74f53

Keep up the great work!
Josh

**Comment by akorchev** [comment]
Indeed we use a tool to script the database and it outputs SQL 2016 compatible script. We will delete all SQL code which isn't required for the demo and is SQL 2016 specific.
